/**
 * Writes the Helmor Kanban Pi extension file and the current board snapshot
 * to the workspace directory before a Pi agent session starts.
 *
 * Extension file:  <cwd>/.pi/extensions/helmor-kanban.ts
 * Board snapshot:  <cwd>/.pi/context/kanban.json
 *
 * The extension is auto-discovered by Pi's DefaultResourceLoader and uses
 * `pi.on("before_agent_start")` to inject the current board state into the
 * system prompt. It also registers the `/new-card` slash command.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { logger } from "./logger.js";

// ---------------------------------------------------------------------------
// Extension source — written verbatim to .pi/extensions/helmor-kanban.ts
// ---------------------------------------------------------------------------

const HELMOR_KANBAN_EXTENSION = `/**
 * Helmor Kanban extension for Pi.
 * Auto-generated by Helmor — do not edit manually.
 * Re-generated each time the Goals AI panel sends a message.
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

export default function (pi: ExtensionAPI) {
  // Inject current Kanban board state into the system prompt before each turn.
  pi.on("before_agent_start", async (event, ctx) => {
    try {
      const raw = await readFile(
        join(ctx.cwd, ".pi", "context", "kanban.json"),
        "utf8",
      );
      // Each entry is a WorkspaceDetail subset — cards are workspaces now.
      const cards = JSON.parse(raw) as Array<{
        id: string;
        title: string;
        lane: string;
        branch?: string | null;
        prUrl?: string | null;
        sessionCount?: number;
      }>;

      // Build context block — start with goal meta if available.
      const contextLines: string[] = [];

      try {
        const metaRaw = await readFile(
          join(ctx.cwd, ".pi", "context", "goal-meta.json"),
          "utf8",
        );
        const meta = JSON.parse(metaRaw) as {
          title?: string;
          description?: string;
        };
        if (meta.title) {
          contextLines.push(\`## Goal: \${meta.title}\`);
          if (meta.description) {
            contextLines.push("", meta.description);
          }
          contextLines.push("");
        }
      } catch {
        // goal-meta.json not present — no goal context to inject.
      }

      if (cards.length === 0) {
        contextLines.push(
          "## Kanban Board",
          "The board is currently empty. Use create_kanban_card to create a workspace card.",
        );
        return {
          systemPrompt:
            event.systemPrompt + "\\n\\n" + contextLines.join("\\n"),
        };
      }

      const byLane = new Map<string, typeof cards>();
      for (const card of cards) {
        if (!byLane.has(card.lane)) byLane.set(card.lane, []);
        byLane.get(card.lane)!.push(card);
      }

      const laneOrder = ["backlog", "in-progress", "review", "done", "canceled"];
      contextLines.push("## Kanban Board", "");
      for (const lane of laneOrder) {
        const laneCards = byLane.get(lane);
        if (!laneCards?.length) continue;
        contextLines.push(\`### \${lane}\`);
        for (const c of laneCards) {
          const branchTag = c.branch ? \` [\${c.branch}]\` : "";
          const prTag = c.prUrl ? " [PR open]" : "";
          const threadsTag = c.sessionCount ? \` [\${c.sessionCount} thread\${c.sessionCount === 1 ? "" : "s"}]\` : "";
          contextLines.push(\`- [workspace:\${c.id}] \${c.title}\${branchTag}\${prTag}\${threadsTag}\`);
        }
        contextLines.push("");
      }
      contextLines.push(
        "Each card is a workspace. Use list_kanban_cards, create_kanban_card, move_kanban_card to manage cards.",
        "Use list_threads(workspace_id), create_thread(workspace_id), get_thread(workspace_id, thread_id), update_thread(workspace_id, thread_id, title) to inspect threads inside any workspace.",
      );

      return { systemPrompt: event.systemPrompt + "\\n\\n" + contextLines.join("\\n") };
    } catch {
      // kanban.json not yet written or unreadable — skip injection silently.
      return {};
    }
  });

  // /new-card slash command — interactive card creation flow.
  pi.registerCommand("new-card", {
    description: "Create a new Kanban card interactively",
    argumentHint: "[title]",
    handler: async (args, ctx) => {
      const rawTitle = args.trim();
      const title =
        rawTitle ||
        (await ctx.ui.input("Card title", "What needs to be done?")) ||
        "";
      if (!title) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      const lane = await ctx.ui.select("Which lane?", [
        "backlog",
        "in-progress",
        "review",
        "done",
        "canceled",
      ]);
      if (!lane) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      const confirmed = await ctx.ui.confirm(
        "Create card?",
        \`"\${title}" will be added to \${lane}.\`,
      );
      if (!confirmed) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      await pi.sendUserMessage(
        \`Create a Kanban card titled "\${title}" in the \${lane} lane.\`,
        { mode: "nextTurn" },
      );
    },
  });
}
`;

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

export type GoalMeta = {
	title?: string;
	description?: string;
};

export async function writeKanbanContext(
	cwd: string,
	cards: unknown[],
	goalMeta?: GoalMeta,
): Promise<void> {
	const piDir = join(cwd, ".pi");
	const extensionsDir = join(piDir, "extensions");
	const contextDir = join(piDir, "context");

	try {
		await Promise.all([
			mkdir(extensionsDir, { recursive: true }),
			mkdir(contextDir, { recursive: true }),
		]);

		const writes: Promise<void>[] = [
			writeFile(
				join(extensionsDir, "helmor-kanban.ts"),
				HELMOR_KANBAN_EXTENSION,
				"utf8",
			),
			writeFile(
				join(contextDir, "kanban.json"),
				JSON.stringify(cards, null, 2),
				"utf8",
			),
		];

		// Always write goal-meta.json (even if empty) so the extension can
		// always read it without a try/catch skip path for the first message.
		writes.push(
			writeFile(
				join(contextDir, "goal-meta.json"),
				JSON.stringify(goalMeta ?? {}, null, 2),
				"utf8",
			),
		);

		await Promise.all(writes);

		logger.debug("Wrote Pi Kanban context files", {
			cwd,
			cardCount: cards.length,
			hasGoalMeta: !!(goalMeta?.title ?? goalMeta?.description),
		});
	} catch (err) {
		// Non-fatal — the agent can still run without context injection.
		logger.info("Failed to write Pi Kanban context files", {
			cwd,
			error: String(err),
		});
	}
}
