/**
 * Writes the Helmor Kanban Pi extension file and the current board snapshot
 * to the workspace directory before a Pi agent session starts.
 *
 * Extension file:  <cwd>/.pi/extensions/helmor-kanban.ts
 * Board snapshot:  <cwd>/.pi/context/kanban.json
 *
 * The extension is auto-discovered by Pi's DefaultResourceLoader and uses
 * `pi.on("before_agent_start")` to inject the current board state into the
 * system prompt. Board cards are child workspaces; this writer accepts both
 * the current child-workspace snapshot and the older GoalCard-like shape, then
 * writes the normalized child-workspace shape for Pi.
 * It also registers the `/new-card` slash command.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { logger } from "./logger.js";

// ---------------------------------------------------------------------------
// Extension source — written verbatim to .pi/extensions/helmor-kanban.ts
// ---------------------------------------------------------------------------

const HELMOR_KANBAN_EXTENSION = `/**
 * Helmor Kanban extension for Pi.
 * Auto-generated by Helmor — do not edit manually.
 * Re-generated each time the Goals AI panel sends a message.
 */
import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

export default function (pi: ExtensionAPI) {
  // Inject current Kanban board state into the system prompt before each turn.
  pi.on("before_agent_start", async (event, ctx) => {
    try {
      const raw = await readFile(
        join(ctx.cwd, ".pi", "context", "kanban.json"),
        "utf8",
      );
      // Each entry is a child-workspace board card. There is no separate card DB.
      const cards = JSON.parse(raw) as Array<{
        id: string;
        title: string;
        lane: string;
        description?: string | null;
        branch?: string | null;
        prUrl?: string | null;
        sessionCount?: number;
        activeSessionId?: string | null;
        activeSessionStatus?: string | null;
        activeSessionAgentType?: string | null;
        assigneeName?: string | null;
      }>;

      // Build context block — start with goal meta if available.
      const contextLines: string[] = [];

      try {
        const metaRaw = await readFile(
          join(ctx.cwd, ".pi", "context", "goal-meta.json"),
          "utf8",
        );
        const meta = JSON.parse(metaRaw) as {
          title?: string;
          description?: string;
        };
        if (meta.title) {
          contextLines.push(\`## Goal: \${meta.title}\`);
          if (meta.description) {
            contextLines.push("", meta.description);
          }
          contextLines.push("");
        }
      } catch {
        // goal-meta.json not present — no goal context to inject.
      }

      contextLines.push(
        "## Goal Orchestration Role",
        "You are Pi, the goal supervisor for this Helmor goal board. Your job is to turn the overarching goal into an executable plan, maintain the Kanban board as the source of truth, and coordinate child-workspace assignees without losing sight of the user's desired outcome.",
        "",
        "Operate in this loop:",
        "1. Understand the goal, success criteria, constraints, and current board state before acting.",
        "2. Break the goal into independent workstreams and create one child workspace card per concrete deliverable or investigation.",
        "3. Start work by using create_kanban_card with a clear prompt when a new assignee should begin, or send_assignee_message when an existing card needs direction. These assignee sends are background starts; do not wait or sleep for the assignee to finish unless the user explicitly asks you to monitor.",
        "4. Keep lanes meaningful: backlog = planned/not started, in-progress = assignee actively working or queued to work, review = needs supervisor/user review, done = completed and verified, canceled = intentionally dropped.",
        "5. Read/summarize assignee threads before reporting status, changing priorities, or marking cards done.",
        "6. Give the user a concise supervisor-level answer: what exists, what is running, what is blocked, what you changed, and the next recommended orchestration step.",
        "",
        "Capabilities and limits:",
		"- You can inspect and mutate the goal board with Kanban tools; each card is a real child workspace, not a single thread.",
		"- You can start child workspace agents by creating a card with a prompt, or coordinate existing assignees with assignee tools. Helmor always assigns child prompts to the same Pi provider/model as this goal supervisor.",
		"- A child workspace/card can contain many threads. Use list_threads(workspace_id) whenever thread identity matters, and do not infer work from lane alone.",
		"- If a thread fails, stalls, or shows model/provider startup errors, create or choose a replacement thread, set it active with set_card_assignee_thread, and route follow-up context to that thread.",
		"- Do not invent progress. If a card has no report, read the thread or say that status is unknown.",
        "- Prefer parallel child workspaces for separable tasks, but keep sequencing explicit for dependent tasks.",
        "",
        "## Goal Board Tools",
        "Use list_kanban_cards, create_kanban_card, move_kanban_card, update_kanban_card to inspect and manage child workspace cards.",
		"Use list_threads(workspace_id), create_thread(workspace_id), get_thread(workspace_id, thread_id), update_thread(workspace_id, thread_id, title), delete_thread(workspace_id, thread_id), and send_thread_message(workspace_id, thread_id, message) to inspect and manage threads inside a child workspace.",
		"Use explicit assignee communication tools: send_assignee_message(card_id, message, priority?, thread_id?), set_card_assignee_thread(card_id, thread_id), read_assignee_thread(card_id, thread_id?, since_message_id?), summarize_assignee_status(card_id), and list_assignees(status?).",
        "Do not treat lane movement as execution. Moving a card only changes planning status; queue an assignee message when you want work, context, or a check-in.",
        "Assignee messages and create-card prompts run in the background. After dispatching parallel work, summarize what you started and let the user know you can check back when assignees report; do not burn tokens by sleeping.",
		"Before reporting global status to the user, poll/read the relevant active assignee thread and compare other threads when a card has multiple sessions. Queue extra context instead of interrupting running work.",
		"Do not keep retrying a known-bad thread. If the latest assistant response is a startup/model/provider failure, route the retry to a clean thread with a known-good model and record the replacement thread id in your handoff.",
        "Assignees report blockers and completion in their own threads using clear headings: Progress, Blocked, Completed, Handoff. Do not assume you saw their work until they write a milestone report.",
        "",
      );

      if (cards.length === 0) {
        contextLines.push(
          "## Kanban Board",
          "The board is currently empty. If the user asks for planning or execution, propose a small work breakdown and use create_kanban_card to create child workspace cards. Include a prompt on cards that should immediately start an assignee.",
        );
        return {
          systemPrompt:
            event.systemPrompt + "\\n\\n" + contextLines.join("\\n"),
        };
      }

      const byLane = new Map<string, typeof cards>();
      for (const card of cards) {
        if (!byLane.has(card.lane)) byLane.set(card.lane, []);
        byLane.get(card.lane)!.push(card);
      }

      const laneOrder = ["backlog", "in-progress", "review", "done", "canceled"];
      contextLines.push("## Kanban Board", "");
      for (const lane of laneOrder) {
        const laneCards = byLane.get(lane);
        if (!laneCards?.length) continue;
        contextLines.push(\`### \${lane}\`);
        for (const c of laneCards) {
          const branchTag = c.branch ? \` [\${c.branch}]\` : "";
          const prTag = c.prUrl ? " [PR open]" : "";
          const threadsTag = c.sessionCount ? \` [\${c.sessionCount} thread\${c.sessionCount === 1 ? "" : "s"}]\` : "";
          const assigneeTag = c.assigneeName ? \` [assignee: \${c.assigneeName}]\` : "";
          const activeStatusTag = c.activeSessionStatus ? \` [active: \${c.activeSessionStatus}\${c.activeSessionAgentType ? \`/\${c.activeSessionAgentType}\` : ""}]\` : "";
          contextLines.push(\`- [workspace:\${c.id}] \${c.title}\${branchTag}\${prTag}\${threadsTag}\${assigneeTag}\${activeStatusTag}\`);
          if (c.description) contextLines.push(\`  Description: \${c.description}\`);
        }
        contextLines.push("");
      }
      contextLines.push(
        "Each card is a child workspace. The workspace id shown in [workspace:<id>] is the id to pass as card_id to move_kanban_card/update_kanban_card and as workspace_id to thread tools.",
      );

      return { systemPrompt: event.systemPrompt + "\\n\\n" + contextLines.join("\\n") };
    } catch {
      // kanban.json not yet written or unreadable — skip injection silently.
      return {};
    }
  });

  // /new-card slash command — interactive card creation flow.
  pi.registerCommand("new-card", {
    description: "Create a new Kanban card interactively",
    argumentHint: "[title]",
    handler: async (args, ctx) => {
      const rawTitle = args.trim();
      const title =
        rawTitle ||
        (await ctx.ui.input("Card title", "What needs to be done?")) ||
        "";
      if (!title) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      const lane = await ctx.ui.select("Which lane?", [
        "backlog",
        "in-progress",
        "review",
        "done",
        "canceled",
      ]);
      if (!lane) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      const confirmed = await ctx.ui.confirm(
        "Create card?",
        \`"\${title}" will be added to \${lane}.\`,
      );
      if (!confirmed) {
        ctx.ui.notify("Card creation cancelled.", "info");
        return;
      }

      await pi.sendUserMessage(
        \`Create a Kanban card titled "\${title}" in the \${lane} lane.\`,
        { mode: "nextTurn" },
      );
    },
  });
}
`;

// ---------------------------------------------------------------------------
// Writer
// ---------------------------------------------------------------------------

export type GoalMeta = {
	title?: string;
	description?: string;
};

export type KanbanContextCard = {
	id: string;
	title: string;
	lane: string;
	description?: string | null;
	branch?: string | null;
	prUrl?: string | null;
	sessionCount?: number;
	activeSessionId?: string | null;
	activeSessionStatus?: string | null;
	activeSessionAgentType?: string | null;
	assigneeName?: string | null;
};

function asRecord(value: unknown): Record<string, unknown> | undefined {
	return value && typeof value === "object" && !Array.isArray(value)
		? (value as Record<string, unknown>)
		: undefined;
}

function optionalString(value: unknown): string | null | undefined {
	if (typeof value === "string") return value;
	return value === null ? null : undefined;
}

function optionalNumber(value: unknown): number | undefined {
	return typeof value === "number" && Number.isFinite(value)
		? value
		: undefined;
}

export function normalizeKanbanContextCards(
	cards: readonly unknown[],
): KanbanContextCard[] {
	const normalized: KanbanContextCard[] = [];
	for (const rawCard of cards) {
		const card = asRecord(rawCard);
		if (!card) continue;

		const id =
			optionalString(card.childWorkspaceId) ??
			optionalString(card.workspaceId) ??
			optionalString(card.id);
		if (!id) continue;

		const title = optionalString(card.title) ?? "Untitled workspace";
		const lane =
			optionalString(card.lane) ?? optionalString(card.status) ?? "backlog";

		normalized.push({
			id,
			title,
			lane,
			description: optionalString(card.description),
			branch: optionalString(card.branch) ?? optionalString(card.branchName),
			prUrl: optionalString(card.prUrl),
			sessionCount: optionalNumber(card.sessionCount),
			activeSessionId: optionalString(card.activeSessionId),
			activeSessionStatus: optionalString(card.activeSessionStatus),
			activeSessionAgentType: optionalString(card.activeSessionAgentType),
			assigneeName: optionalString(card.assigneeName),
		});
	}
	return normalized;
}

export async function writeKanbanContext(
	cwd: string,
	cards: unknown[],
	goalMeta?: GoalMeta,
): Promise<void> {
	const normalizedCards = normalizeKanbanContextCards(cards);
	const piDir = join(cwd, ".pi");
	const extensionsDir = join(piDir, "extensions");
	const contextDir = join(piDir, "context");

	try {
		await Promise.all([
			mkdir(extensionsDir, { recursive: true }),
			mkdir(contextDir, { recursive: true }),
		]);

		const writes: Promise<void>[] = [
			writeFile(
				join(extensionsDir, "helmor-kanban.ts"),
				HELMOR_KANBAN_EXTENSION,
				"utf8",
			),
			writeFile(
				join(contextDir, "kanban.json"),
				JSON.stringify(normalizedCards, null, 2),
				"utf8",
			),
		];

		// Always write goal-meta.json (even if empty) so the extension can
		// always read it without a try/catch skip path for the first message.
		writes.push(
			writeFile(
				join(contextDir, "goal-meta.json"),
				JSON.stringify(goalMeta ?? {}, null, 2),
				"utf8",
			),
		);

		await Promise.all(writes);

		logger.debug("Wrote Pi Kanban context files", {
			cwd,
			cardCount: normalizedCards.length,
			hasGoalMeta: !!(goalMeta?.title ?? goalMeta?.description),
		});
	} catch (err) {
		// Non-fatal — the agent can still run without context injection.
		logger.info("Failed to write Pi Kanban context files", {
			cwd,
			error: String(err),
		});
	}
}
