//! TypeScript / JavaScript module specifier resolver.
//!
//! Handles:
//!   - Relative paths (`./foo`, `../bar`) with implicit extensions and
//!     barrel files (`index.{ts,tsx,js,jsx,mts,cts}`).
//!   - `tsconfig.json` `compilerOptions.paths` aliases (the `@/*` pattern
//!     is used throughout this repo). Tolerates JSON-with-comments via a
//!     pre-pass strip; cheap enough not to depend on a JSONC crate.
//!   - Bare specifiers (`react`, `lodash/fp`) → External.
//!
//! All inputs are workspace-relative; we never touch absolute paths so
//! the resolver is deterministic across machines.

use std::{
    collections::HashSet,
    fs,
    path::{Path, PathBuf},
};

use super::Resolution;

/// Extensions we try when resolving a relative specifier without one.
const TRY_EXTENSIONS: &[&str] = &["ts", "tsx", "js", "jsx", "mts", "cts", "mjs", "cjs"];
const BARREL_NAMES: &[&str] = &["index"];

#[derive(Debug, Clone, Default)]
pub struct TsAlias {
    /// Prefix of the alias key. `@/` for `"@/*": ["src/*"]`. Stripped
    /// from the specifier when checking a match.
    pub key_prefix: String,
    /// Suffix of the alias key (after `*`), usually empty.
    pub key_suffix: String,
    /// Targets: workspace-relative path prefixes that will be joined with
    /// the captured `*` portion of the specifier.
    pub targets: Vec<String>,
}

#[derive(Debug, Clone, Default)]
pub struct TsResolverContext {
    /// Workspace-relative paths that exist in the walk — used to
    /// short-circuit `exists()` checks against the filesystem so we get
    /// hits on files generated by sibling pipelines too (no I/O per
    /// edge).
    pub known_files: HashSet<String>,
    pub aliases: Vec<TsAlias>,
}

pub struct TsResolver<'a> {
    workspace_root: &'a Path,
    ctx: &'a TsResolverContext,
}

impl<'a> TsResolver<'a> {
    pub fn new(workspace_root: &'a Path, ctx: &'a TsResolverContext) -> Self {
        Self {
            workspace_root,
            ctx,
        }
    }

    pub fn resolve(&self, from_file: &str, specifier: &str) -> Resolution {
        if specifier.is_empty() {
            return Resolution::Unknown;
        }

        if specifier.starts_with("./") || specifier.starts_with("../") {
            if let Some(path) = self.resolve_relative(from_file, specifier) {
                return Resolution::File {
                    relative_path: path,
                };
            }
            return Resolution::Unknown;
        }

        // Try aliases before falling back to "external bare specifier".
        for alias in &self.ctx.aliases {
            if let Some(rest) = strip_alias(specifier, alias) {
                for target in &alias.targets {
                    let candidate = join_workspace(target, &rest);
                    if let Some(resolved) = self.match_known_file(&candidate) {
                        return Resolution::File {
                            relative_path: resolved,
                        };
                    }
                }
            }
        }

        // Looks like a bare external package (or a node-builtin).
        let pkg = root_package_name(specifier);
        Resolution::External { package: pkg }
    }

    fn resolve_relative(&self, from_file: &str, specifier: &str) -> Option<String> {
        let from_dir = Path::new(from_file)
            .parent()
            .unwrap_or_else(|| Path::new(""));
        let mut joined = from_dir.to_path_buf();
        joined.push(specifier);
        let normalized = normalize_path(&joined);
        self.match_known_file(&normalized)
    }

    fn match_known_file(&self, candidate: &str) -> Option<String> {
        let candidate = candidate.trim_end_matches('/');
        // 1. Exact match.
        if self.ctx.known_files.contains(candidate) {
            return Some(candidate.to_string());
        }
        // 2. With extension.
        for ext in TRY_EXTENSIONS {
            let with_ext = format!("{candidate}.{ext}");
            if self.ctx.known_files.contains(&with_ext) {
                return Some(with_ext);
            }
        }
        // 3. Barrel file inside a directory.
        for barrel in BARREL_NAMES {
            for ext in TRY_EXTENSIONS {
                let barrel_path = format!("{candidate}/{barrel}.{ext}");
                if self.ctx.known_files.contains(&barrel_path) {
                    return Some(barrel_path);
                }
            }
        }
        // 4. Touch disk as a last resort — covers files outside the
        //    known set (e.g. .css imports that the walker doesn't list).
        let abs = self.workspace_root.join(candidate);
        if abs.is_file() {
            return Some(candidate.to_string());
        }
        None
    }
}

fn strip_alias(specifier: &str, alias: &TsAlias) -> Option<String> {
    if !specifier.starts_with(&alias.key_prefix) {
        return None;
    }
    let after_prefix = &specifier[alias.key_prefix.len()..];
    if !alias.key_suffix.is_empty() && !after_prefix.ends_with(&alias.key_suffix) {
        return None;
    }
    let trimmed = if alias.key_suffix.is_empty() {
        after_prefix
    } else {
        &after_prefix[..after_prefix.len() - alias.key_suffix.len()]
    };
    Some(trimmed.to_string())
}

fn join_workspace(target: &str, rest: &str) -> String {
    let target = target.trim_end_matches('/');
    if rest.is_empty() {
        target.to_string()
    } else {
        format!("{target}/{}", rest.trim_start_matches('/'))
    }
}

fn root_package_name(specifier: &str) -> String {
    if let Some(rest) = specifier.strip_prefix('@') {
        // Scoped package: keep `@scope/name`.
        if let Some(slash) = rest.find('/') {
            if let Some(second_slash) = rest[slash + 1..].find('/') {
                return format!("@{}", &rest[..slash + 1 + second_slash]);
            }
            return format!("@{rest}");
        }
        return format!("@{rest}");
    }
    specifier.split('/').next().unwrap_or(specifier).to_string()
}

fn normalize_path(path: &Path) -> String {
    let mut out: Vec<&std::ffi::OsStr> = Vec::new();
    for component in path.components() {
        match component {
            std::path::Component::ParentDir => {
                out.pop();
            }
            std::path::Component::CurDir => {}
            std::path::Component::Normal(part) => out.push(part),
            std::path::Component::RootDir | std::path::Component::Prefix(_) => {
                // Shouldn't happen for our relative inputs.
            }
        }
    }
    PathBuf::from_iter(out).to_string_lossy().replace('\\', "/")
}

/// Walks the workspace for `tsconfig.json` files and merges their
/// `compilerOptions.paths` into a flat alias list.
pub fn discover_aliases(workspace_root: &Path) -> Vec<TsAlias> {
    let mut configs: Vec<PathBuf> = Vec::new();
    discover_configs(workspace_root, workspace_root, &mut configs);

    let mut all = Vec::new();
    for path in configs {
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        let stripped = strip_json_comments(&text);
        let Ok(value) = serde_json::from_str::<serde_json::Value>(&stripped) else {
            continue;
        };
        let base_dir = path.parent().unwrap_or(workspace_root).to_path_buf();
        let base_url = value
            .pointer("/compilerOptions/baseUrl")
            .and_then(|v| v.as_str())
            .unwrap_or(".");
        let base = base_dir.join(base_url);
        let Ok(rel_base) = base.strip_prefix(workspace_root).map(|p| p.to_path_buf()) else {
            continue;
        };
        let rel_base_str = rel_base.to_string_lossy().replace('\\', "/");
        if let Some(paths_map) = value
            .pointer("/compilerOptions/paths")
            .and_then(|v| v.as_object())
        {
            for (key, targets) in paths_map {
                let Some(targets) = targets.as_array() else {
                    continue;
                };
                let Some((prefix, suffix)) = split_glob(key) else {
                    continue;
                };
                let resolved_targets: Vec<String> = targets
                    .iter()
                    .filter_map(|t| t.as_str())
                    .filter_map(|t| {
                        let (tp, _ts) = split_glob(t)?;
                        let joined = join_workspace(&rel_base_str, &tp);
                        Some(joined)
                    })
                    .collect();
                if resolved_targets.is_empty() {
                    continue;
                }
                all.push(TsAlias {
                    key_prefix: prefix,
                    key_suffix: suffix,
                    targets: resolved_targets,
                });
            }
        }
    }
    all
}

fn discover_configs(workspace_root: &Path, current: &Path, out: &mut Vec<PathBuf>) {
    let Ok(read_dir) = fs::read_dir(current) else {
        return;
    };
    for entry in read_dir.flatten() {
        let path = entry.path();
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_dir() {
            if super::super::walker::MAX_FILES == 0 {
                // never; just here so the import path is exercised
            }
            let Some(name) = path.file_name().and_then(|v| v.to_str()) else {
                continue;
            };
            if matches!(
                name,
                ".git" | "node_modules" | "dist" | "build" | "target" | ".next" | ".venv"
            ) || (name.starts_with('.') && path != workspace_root)
            {
                continue;
            }
            discover_configs(workspace_root, &path, out);
        } else if file_type.is_file()
            && path.file_name().and_then(|v| v.to_str()) == Some("tsconfig.json")
        {
            out.push(path);
        }
    }
}

fn split_glob(key: &str) -> Option<(String, String)> {
    if let Some(idx) = key.find('*') {
        let prefix = key[..idx].to_string();
        let suffix = key[idx + 1..].to_string();
        Some((prefix, suffix))
    } else {
        // Non-glob alias: treat as exact-match key.
        Some((key.to_string(), String::new()))
    }
}

/// Tolerant comment stripper for tsconfig.json — accepts // and /* */
/// without trying to be a full JSON5 parser. Preserves comments inside
/// strings.
pub fn strip_json_comments(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    let bytes = input.as_bytes();
    let mut i = 0;
    let mut in_string = false;
    let mut string_quote: u8 = b'"';
    while i < bytes.len() {
        let c = bytes[i];
        if in_string {
            out.push(c as char);
            if c == b'\\' && i + 1 < bytes.len() {
                out.push(bytes[i + 1] as char);
                i += 2;
                continue;
            }
            if c == string_quote {
                in_string = false;
            }
            i += 1;
            continue;
        }
        if c == b'"' || c == b'\'' {
            in_string = true;
            string_quote = c;
            out.push(c as char);
            i += 1;
            continue;
        }
        if c == b'/' && i + 1 < bytes.len() {
            match bytes[i + 1] {
                b'/' => {
                    while i < bytes.len() && bytes[i] != b'\n' {
                        i += 1;
                    }
                    continue;
                }
                b'*' => {
                    i += 2;
                    while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                        i += 1;
                    }
                    i = (i + 2).min(bytes.len());
                    continue;
                }
                _ => {}
            }
        }
        out.push(c as char);
        i += 1;
    }
    // Trailing-comma tolerance — naive, but tsconfig is the only consumer.
    let mut cleaned = String::with_capacity(out.len());
    let bytes = out.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b',' {
            let mut j = i + 1;
            while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                j += 1;
            }
            if j < bytes.len() && (bytes[j] == b']' || bytes[j] == b'}') {
                i += 1;
                continue;
            }
        }
        cleaned.push(bytes[i] as char);
        i += 1;
    }
    cleaned
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx_with(files: &[&str], aliases: Vec<TsAlias>) -> TsResolverContext {
        TsResolverContext {
            known_files: files.iter().map(|f| f.to_string()).collect(),
            aliases,
        }
    }

    #[test]
    fn resolves_relative_with_extension() {
        let ctx = ctx_with(&["src/foo.ts", "src/bar/index.tsx"], vec![]);
        let r = TsResolver::new(Path::new("/x"), &ctx);
        match r.resolve("src/index.ts", "./foo") {
            Resolution::File { relative_path } => assert_eq!(relative_path, "src/foo.ts"),
            other => panic!("expected File, got {other:?}"),
        }
    }

    #[test]
    fn resolves_barrel_directory_import() {
        let ctx = ctx_with(&["src/bar/index.tsx"], vec![]);
        let r = TsResolver::new(Path::new("/x"), &ctx);
        match r.resolve("src/index.ts", "./bar") {
            Resolution::File { relative_path } => assert_eq!(relative_path, "src/bar/index.tsx"),
            other => panic!("expected File, got {other:?}"),
        }
    }

    #[test]
    fn resolves_at_slash_alias_to_src() {
        let alias = TsAlias {
            key_prefix: "@/".into(),
            key_suffix: String::new(),
            targets: vec!["src".into()],
        };
        let ctx = ctx_with(&["src/lib/api.ts"], vec![alias]);
        let r = TsResolver::new(Path::new("/x"), &ctx);
        match r.resolve("src/App.tsx", "@/lib/api") {
            Resolution::File { relative_path } => assert_eq!(relative_path, "src/lib/api.ts"),
            other => panic!("expected File, got {other:?}"),
        }
    }

    #[test]
    fn bare_specifier_is_external() {
        let ctx = ctx_with(&[], vec![]);
        let r = TsResolver::new(Path::new("/x"), &ctx);
        match r.resolve("src/App.tsx", "react") {
            Resolution::External { package } => assert_eq!(package, "react"),
            other => panic!("expected External, got {other:?}"),
        }
    }

    #[test]
    fn scoped_external_package_keeps_scope() {
        let ctx = ctx_with(&[], vec![]);
        let r = TsResolver::new(Path::new("/x"), &ctx);
        match r.resolve("src/App.tsx", "@radix-ui/react-dialog") {
            Resolution::External { package } => assert_eq!(package, "@radix-ui/react-dialog"),
            other => panic!("expected External, got {other:?}"),
        }
    }

    #[test]
    fn strip_json_comments_handles_line_and_block() {
        let input = r#"{
            // line comment
            "key": "value", /* block */
            "trailing": "x",
        }"#;
        let cleaned = strip_json_comments(input);
        let parsed: serde_json::Value = serde_json::from_str(&cleaned).unwrap();
        assert_eq!(parsed["key"], "value");
        assert_eq!(parsed["trailing"], "x");
    }
}
